### ISSUE TITLE
Feedback Course 2 - EHDEN Foundation

### ISSUE THREAD

**Issue by lhjohn** [EHDEN/Academy#64]
Original feedback: [EHDEN Foundation Feedback.zip](https://github.com/EHDEN/Academy/files/4270105/EHDEN.Foundation.Feedback.zip)

**Course structure (_progression and difficulty_):**
- [x] Course is too long - often mentioned in reference to the length of some videos (5x)
- [x] Course has too much repetition (7x)
- [x] The marking scheme for the exam seemed unusual. There seemed to be part marks if you selected 1 too many answers (as i did for Q1), but 0 marks if you selected 1 too few answers (as I did for Q2).
- [x] The exam! It was a bit frustrating to read "You pass if your score is higher than 2.5/3.0.", but to understand at the end that, a single error out of the 13 questions (checkboxes) would make me fail.

**Course presentation (_use of of text, audio and video_):**
- [x] Summarise content of videos in written form or provide slide-decks (3x)
- [x] (Some) videos are too long (1x)

**Course content (_target audience and material_):**
- [x] Explanation of EHDEN and other institutions is too long/boring (3x)
- [x] Make clear that course is aimed at a managing audience and tools will be discussed later
- [x] It was a too theoretical (1x)
- [x] The course said that IMI is the largest PPP in the world IN LIFE SCIENCES, but the exam question was more general than that. The exam question about the EHDEN Academy being open to people outside the EHDEN community confused me. I guess it depends on how you define the 'EHDEN community', and how open the Academy is planned to be.

**Technical feedback**
- [ ] Make activities automatically complete.

**Comment by JellePraet** [comment]
* Modified the exam so that it's now 13 seperate questions and you need 10/13 to pass the exam. This fixes those 2 questions
* I've marked quite a few videos as optional (since they repeat what was mentionned in the text and figures. 
* By marking videos as optional, the repitition of content in videos that's also written out should be solved.
* Changed the introduction so that it's more clear that this is an introductory, non-technical course.
* Added annotation to the videos in the course. I did not do this for the optional videos of the EU OHDSI symposium however.
What I didnt change:
* Explenation of EHDEN / other institutions being boring => It's not as sexy as the actual science off course, you have to know it if you want to understand how EHDEN functions. Besides, it's not that long...

**Comment by JellePraet** [comment]
@lhjohn : That last comment "Make activities auto-complete" => Is that something you can fix for me, since I don't know how to set that.

**Comment by lhjohn** [comment]
Yes, I fixed that.
